#!/usr/bin/env python3
"""Build the FairPay v0.4.1 demo video with detailed educational captions.

Companion to the earlier brief-caption UI demo. Per the reviewer's subtitle-style
requirements, each caption is a complete-sentence block (bold heading + 2-3 body
lines) that explains the feature, the benefit, and the technical detail.

Rendered at 1920x1080 @ 30fps on a clean dark-navy background with libass:
white text, black outline, bottom center (title cards centered), sized for mobile
readability. The prior UI recording (media/fairpay_ui_demo.mp4) already has its own
burned-in bottom captions, so it cannot be reused as a base for new bottom subtitles.

Usage:
  python scripts/build_fairpay_video_v2.py            # full video
  python scripts/build_fairpay_video_v2.py preview    # first 3 captions only
"""
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MEDIA = ROOT / "media"
ASS = MEDIA / "fairpay_demo_v2.ass"
OUT = MEDIA / "fairpay_demo_v2.mp4"

W, H, FPS = 1920, 1080, 30
FONT = "DejaVu Sans"

# (start, end, heading, [body lines...], centered)
CAPTIONS = [
    (0, 5, "FairPay v0.4.1",
     ["AI-Audited Payroll on GenLayer",
      "Multi-Gateway Evidence & Reserved Liability",
      "StudioNet Deployment"], True),
    (5, 15, "Multi-Gateway Evidence Allowlist",
     ["Replaced single ipfs.io prefix with",
      "4 HTTPS gateways: pinata, ipfs.io,",
      "dweb.link, w3s.link"], False),
    (15, 25, "Strict URL Validation",
     ["Anchored regex rejects lookalike hosts,",
      "userinfo, subdomains, query strings",
      "before any state change"], False),
    (25, 35, "Lookalike Attack Prevention",
     ["ipfs.io.evil.com is rejected because",
      "the host must exactly match",
      "one of the 4 allowed gateways"], False),
    (35, 45, "Content-Derived Integrity",
     ["SHA256 seal covers fetched bytes",
      "so which gateway served the content",
      "is irrelevant to settlement"], False),
    (45, 55, "Reserved Liability Protection",
     ["Employer recovery cannot defund",
      "a live appeal window - the contract",
      "reserves max reachable payout"], False),
    (55, 65, "Dynamic Budget Protection",
     ["Hours \u00d7 Rate \u00d7 1.25 is reserved",
      "while any higher outcome is reachable",
      "dropping to exact pay only when final"], False),
    (65, 75, "All Changes Verified",
     ["79 passing tests (27 unit + 52 Direct Mode)",
      "11-tx on-chain steward scenario",
      "Contract: 0xb16d...673AF4"], False),
]

HEADER = (
    "[Script Info]\n"
    "; generated by scripts/build_fairpay_video_v2.py (detailed educational captions)\n"
    "ScriptType: v4.00+\n"
    f"PlayResX: {W}\nPlayResY: {H}\nWrapStyle: 0\nScaledBorderAndShadow: yes\n\n"
    "[V4+ Styles]\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
    "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
    "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
    f"Style: Cap,{FONT},46,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,"
    "0,0,1,4,2,2,80,80,90,1\n"
    f"Style: Title,{FONT},60,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,"
    "0,0,1,5,2,5,80,80,80,1\n\n"
    "[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
)


def esc(t):
    return t.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def ts(sec):
    h = int(sec // 3600)
    m = int((sec % 3600) // 60)
    s = sec % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def caption_text(heading, body):
    parts = [f"{{\\b1\\fs70}}{esc(heading)}{{\\b0\\fs46}}"]
    parts += [esc(b) for b in body]
    return "\\N".join(parts)


def build_ass(captions):
    events = []
    for start, end, heading, body, centered in captions:
        style = "Title" if centered else "Cap"
        events.append(f"Dialogue: 0,{ts(start)},{ts(end)},{style},,0,0,0,,{caption_text(heading, body)}\n")
    ASS.write_text(HEADER + "".join(events))


def render(captions, out, limit=None):
    build_ass(captions)
    dur = limit if limit is not None else CAPTIONS[-1][1]
    bg = f"color=c=0x0b1220:s={W}x{H}:r={FPS}:d={dur}"
    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
           "-f", "lavfi", "-i", bg,
           "-vf", f"subtitles={ASS}",
           "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "medium",
           "-crf", "20", "-r", str(FPS), "-t", str(dur), str(out)]
    subprocess.run(cmd, check=True)


def grab_frame(t, out_png, src):
    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
           "-ss", str(t), "-i", str(src), "-frames:v", "1", str(out_png)]
    subprocess.run(cmd, check=True)


def main():
    preview = len(sys.argv) > 1 and sys.argv[1] == "preview"
    if preview:
        caps = [c for c in CAPTIONS if c[1] <= 25]
        prev = MEDIA / "fairpay_demo_v2_preview.mp4"
        render(caps, prev, limit=25)
        for t, name in [(2.5, "cap1_title"), (10.0, "cap2_allowlist"), (20.0, "cap3_strict")]:
            grab_frame(t, MEDIA / f"preview_{name}.png", prev)
        print(f"wrote {prev.name} + preview frames")
        return
    total = CAPTIONS[-1][1]
    render(CAPTIONS, OUT)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size/1e6:.2f} MB, ~{total}s)")


if __name__ == "__main__":
    main()
