#!/usr/bin/env python3
"""Overlay the FairPay v0.4.1 educational captions onto the clean 1080p UI recording.

Input:  frontend/shots/fairpay_ui_clean.mp4 (recorded by capture_v3.mjs, no captions)
Output: media/fairpay_demo_v3.mp4 (UI visible, educational subtitles in a lower third)

Captions are white text with a black outline and a soft shadow, bottom-center but
raised (MarginV) so they sit in the lower band and do not cover the controls being
described (each section is scrolled to the top during its caption window).

Usage:
  python scripts/build_fairpay_video_v3.py           # full render
  python scripts/build_fairpay_video_v3.py preview   # draft + overlap-check frames
"""
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MEDIA = ROOT / "media"
CLEAN = ROOT / "frontend" / "shots" / "fairpay_ui_clean.mp4"
ASS = MEDIA / "fairpay_demo_v3.ass"
OUT = MEDIA / "fairpay_demo_v3.mp4"

W, H, FPS = 1920, 1080, 30
FONT = "DejaVu Sans"

# (start, end, heading, [body lines...], centered)
CAPTIONS = [
    (0, 5, "FairPay v0.4.1",
     ["AI-Audited Payroll on GenLayer",
      "Multi-Gateway Evidence & Reserved Liability",
      "StudioNet Deployment"], True),
    (5, 15, "Multi-Gateway Evidence Allowlist",
     ["Replaced single ipfs.io prefix with",
      "4 HTTPS gateways: pinata, ipfs.io,",
      "dweb.link, w3s.link"], False),
    (15, 25, "Strict URL Validation",
     ["Anchored regex rejects lookalike hosts,",
      "userinfo, subdomains, query strings",
      "before any state change"], False),
    (25, 35, "Lookalike Attack Prevention",
     ["ipfs.io.evil.com is rejected because",
      "the host must exactly match",
      "one of the 4 allowed gateways"], False),
    (35, 45, "Content-Derived Integrity",
     ["SHA256 seal covers fetched bytes",
      "so which gateway served the content",
      "is irrelevant to settlement"], False),
    (45, 55, "Reserved Liability Protection",
     ["Employer recovery cannot defund",
      "a live appeal window - the contract",
      "reserves max reachable payout"], False),
    (55, 65, "Dynamic Budget Protection",
     ["Hours \u00d7 Rate \u00d7 1.25 is reserved",
      "while any higher outcome is reachable",
      "dropping to exact pay only when final"], False),
    (65, 75, "All Changes Verified",
     ["79 passing tests (27 unit + 52 Direct Mode)",
      "11-tx on-chain steward scenario",
      "Contract: 0xb16d...673AF4"], False),
]

HEADER = (
    "[Script Info]\n"
    "; generated by scripts/build_fairpay_video_v3.py (UI + educational lower-third captions)\n"
    "ScriptType: v4.00+\n"
    f"PlayResX: {W}\nPlayResY: {H}\nWrapStyle: 0\nScaledBorderAndShadow: yes\n\n"
    "[V4+ Styles]\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, "
    "BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, "
    "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n"
    # White text, black outline, soft shadow, bottom-center raised (MarginV=95).
    f"Style: Cap,{FONT},42,&H00FFFFFF,&H000000FF,&H00000000,&H96000000,0,0,0,0,100,100,"
    "0,0,1,4,3,2,90,90,95,1\n"
    f"Style: Title,{FONT},60,&H00FFFFFF,&H000000FF,&H00000000,&H96000000,0,0,0,0,100,100,"
    "0,0,1,5,3,5,90,90,90,1\n\n"
    "[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
)


def esc(t):
    return t.replace("\\", "\\\\").replace("{", "\\{").replace("}", "\\}")


def ts(sec):
    h = int(sec // 3600)
    m = int((sec % 3600) // 60)
    s = sec % 60
    return f"{h}:{m:02d}:{s:05.2f}"


def caption_text(heading, body):
    parts = [f"{{\\b1\\fs64}}{esc(heading)}{{\\b0\\fs42}}"]
    parts += [esc(b) for b in body]
    return "\\N".join(parts)


def build_ass(captions):
    events = []
    for start, end, heading, body, centered in captions:
        style = "Title" if centered else "Cap"
        events.append(f"Dialogue: 0,{ts(start)},{ts(end)},{style},,0,0,0,,{caption_text(heading, body)}\n")
    ASS.write_text(HEADER + "".join(events))


def render(out):
    if not CLEAN.exists():
        sys.exit(f"missing clean UI recording: {CLEAN} (run: node frontend/capture_v3.mjs)")
    build_ass(CAPTIONS)
    cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
           "-i", str(CLEAN),
           "-vf", f"subtitles={ASS}",
           "-c:v", "libx264", "-pix_fmt", "yuv420p", "-preset", "medium",
           "-crf", "19", "-r", str(FPS), "-movflags", "+faststart", str(out)]
    subprocess.run(cmd, check=True)


def grab_frame(src, t, out_png):
    subprocess.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                    "-ss", str(t), "-i", str(src), "-frames:v", "1", str(out_png)], check=True)


def main():
    preview = len(sys.argv) > 1 and sys.argv[1] == "preview"
    if preview:
        draft = MEDIA / "fairpay_demo_v3_draft.mp4"
        render(draft)
        # Overlap-sensitive moments: lookalike rejection (section 1) and calculator (section 2).
        for t, name in [(30.0, "lookalike"), (58.0, "calculator")]:
            grab_frame(draft, t, MEDIA / f"preview_{name}.png")
        print(f"draft: {draft.name} + preview frames")
        return
    render(OUT)
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size/1e6:.2f} MB, ~{CAPTIONS[-1][1]}s)")


if __name__ == "__main__":
    main()
